use master
go
create database ESPINOLA_DB
go
use ESPINOLA_DB
go

USE ESPINOLA_DB
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
GO
CREATE TABLE dbo.CLIENTES
	(
	DNI int NOT NULL,
	Nombre varchar(50) NOT NULL,
	Apellido varchar(50) NOT NULL,
	Direccion varchar(50) NOT NULL,
	CodPostal int NOT NULL,
	FNacimiento date NOT NULL,
	Localidad varchar(50) NOT NULL,
	Mail varchar(50) NOT NULL,
	Provincia varchar(50) NOT NULL,
	Celular varchar(50) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.CLIENTES ADD CONSTRAINT
	PK_CLIENTES PRIMARY KEY CLUSTERED 
	(
	DNI
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE TABLE dbo.ARTICULOS
	(
	Codigo int NOT NULL,
	Descripcion varchar(50) NOT NULL,
	idMarca int NOT NULL,
	idTipo int NOT NULL,
	Precio float(53) NOT NULL,
	Costo float(53) NOT NULL,
	IVA float(53) NULL,
	StockMin int NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.ARTICULOS ADD CONSTRAINT
	PK_ARTICULOS PRIMARY KEY CLUSTERED 
	(
	Codigo
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.ARTICULOS SET (LOCK_ESCALATION = TABLE)
GO