use master
go
create database COMERCIO_DB
go
use COMERCIO_DB
go

USE COMERCIO_DB
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
GO
CREATE TABLE dbo.CLIENTES
	(
	DNI int NOT NULL,
	Nombre varchar(50) NOT NULL,
	Apellido varchar(50) NOT NULL,
	Direccion varchar(50) NOT NULL,
	CodPostal int NOT NULL,
	FNacimiento date NOT NULL,
	Localidad varchar(50) NOT NULL,
	Mail varchar(50) NOT NULL,
	Provincia varchar(50) NOT NULL,
	Celular varchar(50) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.CLIENTES ADD CONSTRAINT
	PK_CLIENTES PRIMARY KEY CLUSTERED 
	(
	DNI
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
